Repository Soma-Technologies-Inc/visitAfrica-backend, pull requests merged in 2020-12, with the labels that each got.

#20 #175494062 User registration and email verification
  .babelrc
  .env
  .env.example
  .eslintrc.json
  .gitignore
  .travis.yml
  package.json
  preview.html
  src/controllers/auth.controller.js
  src/database/index.js
  src/database/migrations/20201129004549-create-user.js
  src/database/migrations/index.js
  src/database/models/user.js
  src/routes/auth.route.js
  src/routes/index.js
  src/server.js
  src/services/bcrypt.service.js
  src/services/index.js
  src/services/mail.service.js
  src/services/response.service.js
  src/services/token.service.js
  src/services/user.service.js
  src/tests/auth/auth.test.js
  src/tests/fixtures/user.fixture.js
  src/tests/test.js
  src/validations/index.js
Labels: team-mates-review, work in progress

#21 #175494169 Users should receive descriptive signup validation errors
  .travis.yml
  package.json
  preview.html
  src/controllers/auth.controller.js
  src/database/migrations/20201129004549-create-user.js
  src/database/models/index.js
  src/helpers/index.js
  src/middlewares/index.js
  src/middlewares/user.midleware.js
  src/routes/auth.route.js
  src/server.js
  src/services/user.service.js
  src/tests/auth/auth.test.js
  src/tests/auth/signup.test.js
  src/tests/fixtures/user.fixture.js
  src/validations/index.js
  src/validations/user.validation.js
Labels: peer-review

#19 #175494064 updating profile page
  .gitignore
  preview.html
  src/controllers/auth.controller.js
  src/controllers/user.controller.js
  src/middlewares/protect-route.middleware.js
  src/middlewares/user.middleware.js
  src/routes/auth.route.js
  src/routes/index.js
  src/routes/user.route.js
  src/services/mail.service.js
  src/services/token.service.js
  src/services/user.service.js
  src/tests/app/app.test.js
  src/tests/auth/signup.test.js
  src/tests/fixtures/database.fixture.js
  src/tests/fixtures/user.fixture.js
  src/tests/users/get-users.test.js
  src/tests/users/update-user.test.js
  src/validations/user.validation.js
Labels: peer-review

#16 #175494059 Login with Email and Password
  .babelrc
  .env.example
  .travis.yml
  package.json
  preview.html
  src/controllers/auth.controller.js
  src/database/config/config.js
  src/database/seeders/20201209104656-demo-user.js
  src/database/seeders/index.js
  src/middlewares/user.middleware.js
  src/routes/auth.route.js
  src/services/user.service.js
  src/tests/auth/login.test.js
  src/tests/auth/signup.test.js
  src/tests/main.test.js
  src/tests/test.js
  src/validations/user.validation.js
Labels: peer-review

#25 #176003882 ft: user verification
  .env.example
  .gitignore
  .travis.yml
  README.md
  package.json
  src/controllers/auth.controller.js
  src/routes/auth.route.js
  src/services/mail.service.js
  src/services/user.service.js
  src/tests/auth/signup.test.js
  src/tests/auth/user-verification.test.js
  src/tests/fixtures/user.fixture.js
  src/tests/main.test.js
  src/tests/users/get-users.test.js
  src/tests/users/update-user.test.js
Labels: peer-review

#27 #175494061 ft:login with google and facebook
  package.json
  src/config/passport.config.js
  src/controllers/auth.controller.js
  src/middlewares/user.middleware.js
  src/routes/auth.route.js
  src/tests/auth/oauth.test.js
  src/tests/fixtures/user.fixture.js
  src/tests/main.test.js
  src/tests/users/get-users.test.js
  src/tests/users/update-user.test.js
Labels: peer-review

#18 #175494076 User Role Settings
  .env.example
  src/controllers/auth.controller.js
  src/controllers/user.controller.js
  src/database/migrations/20201129004549-create-user.js
  src/database/models/user.js
  src/database/seeders/20201209104656-demo-user.js
  src/middlewares/user.middleware.js
  src/routes/user.route.js
  src/services/user.service.js
  src/tests/auth/signup.test.js
  src/tests/fixtures/user.fixture.js
  src/tests/main.test.js
  src/tests/test.js
  src/tests/users/user-role.test.js
  src/validations/user.validation.js
Labels: mentor-review

#40 fix heroku issues
  package.json
Labels: work in progress

#39 #175494065 Ft reset password
  Procfile
  src/controllers/auth.controller.js
  src/routes/auth.route.js
  src/services/mail.service.js
  src/tests/auth/oauth.test.js
  src/tests/auth/resetpassword.test.js
  src/tests/fixtures/user.fixture.js
  src/tests/main.test.js
  src/tests/users/manage-user.test.js
  src/tests/users/user-role.test.js
  src/validations/user.validation.js
Labels: peer-review

#36 #175494074 ft:Users should be able to make multi city request
  package.json
  src/controllers/trip.controller.js
  src/database/migrations/20201129004549-create-user.js
  src/database/migrations/20201214103345-create-trips.js
  src/database/migrations/20201218125054-trips.js
  src/database/migrations/20201220054413-create-line-manager.js
  src/database/migrations/20201221144646-create-location.js
  src/database/models/location.js
  src/database/models/trips.js
  src/database/models/user.js
  src/database/seeders/20201209104656-demo-user.js
  src/database/seeders/20201221153626-locations.js
  src/middlewares/protect-route.middleware.js
  src/middlewares/trip.middleware.js
  src/middlewares/user.middleware.js
  src/routes/index.js
  src/routes/trip.route.js
  src/services/location.service.js
  src/services/trip.service.js
  src/tests/auth/oauth.test.js
  src/tests/fixtures/user.fixture.js
  src/tests/main.test.js
  src/tests/trip/multi-city.test.js
  src/tests/users/manage-user.test.js
  src/tests/users/update-user.test.js
  src/tests/users/user-role.test.js
  src/validations/multicity.validation.js
Labels: team-mates-review

#37 #175494070 Return Trip
  src/controllers/trip.controller.js
  src/middlewares/trip.middlewares.js
  src/routes/trip.route.js
  src/services/trip.service.js
  src/tests/fixtures/user.fixture.js
  src/tests/main.test.js
  src/tests/test.js
  src/tests/trip/multi-city.test.js
  src/tests/trip/trip.test.js
  src/tests/users/get-users.test.js
  src/tests/users/user-role.test.js
  src/validations/trip.validation.js
Labels: peer-review
