Repository Soma-Technologies-Inc/visitAfrica-backend, pull requests merged in 2020-11, with the labels that each got.

#1 ch-configuring-eslint: configuringeslint
  .eslintrc.json
  .gitignore
  package.json
  src/controllers/index.js
  src/database/index.js
  src/helpers/index.js
  src/middlewares/index.js
  src/routes/index.js
  src/server.js
  src/services/index.js
Labels: team-mates-review

#2 Setting up Hound CI
  .eslintrc.json
  .hound.yml
  README.md
Labels: peer-review

#6 configuring code climate
  .codeclimate.yml
Labels: completed

#9 configuring express and change some babel dependency
  .babelrc
  package.json
  src/server.js
Labels: Priority, team-mates-review

#10 #175494041 Seting up mocha and chai for testing
  .babelrc
  .eslintrc.json
  .gitignore
  .hound.yml
  package.json
  src/server.js
  src/tests/test.js
Labels: team-mates-review

#11 #175815411 Bug: solving eslint bug
  .hound.yml
  package.json
Labels: mentor-review

#12 #175494031 Integrate TravisCI with badge attached to readme
  .travis.yml
  README.md
Labels: team-mates-review

#7 #175494032 making code coverage
  .coveralls.yml
  .eslintrc.json
  .gitignore
  README.md
  package.json
Labels: team-mates-review

#13 #175835392 Update README
  README.md
Labels: team-mates-review

#14 #175494034 Adding API Documentation
  README.md
Labels: team-mates-review
